version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: .build/dockerfiles/local/Dockerfile.api
    container_name: api
    hostname: api
    restart: always
    ports:
      - "80:80"
    volumes:
      - .:/app
    working_dir: /app/
    env_file: .env

  db:
    image: postgres:10
    container_name: db
    hostname: db
    restart: unless-stopped
    volumes:
      - db:/var/lib/postgresql/data
    expose:
      - 5432
    env_file:
      - .build/env/local/.env.db
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "admin"]

volumes:
  db: