version: "3.9"

services:
  web:
    build: .
    restart: always
    ports:
      - "80:80"
    volumes:
      - .:/django_Infrastructure
    depends_on:
      - db

  db:
    image: postgres:13.4
    container_name: postgres
    hostname: postgres
    restart: always
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=infra_db
      - POSTGRES_USER=mason
      - POSTGRES_PASSWORD=1234qwer
volumes:
  db: